// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxfFT9eJ7ujFBZc0pnpNH3U27TR7o2DS8',
    appId: '1:1012598441896:web:1eff28e7e863078ce8bf9d',
    messagingSenderId: '1012598441896',
    projectId: 'iqoute-d1839',
    authDomain: 'iqoute-d1839.firebaseapp.com',
    storageBucket: 'iqoute-d1839.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7K9ABoNQSk9dRdFM-81aTw6bFJYVTtyY',
    appId: '1:1012598441896:android:bf80a4d36b2ad362e8bf9d',
    messagingSenderId: '1012598441896',
    projectId: 'iqoute-d1839',
    storageBucket: 'iqoute-d1839.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2yw-0UrAlgtAd-LdVoyhwoXeXT78ojE',
    appId: '1:1012598441896:ios:37d1fc04abbefed9e8bf9d',
    messagingSenderId: '1012598441896',
    projectId: 'iqoute-d1839',
    storageBucket: 'iqoute-d1839.appspot.com',
    iosClientId: '1012598441896-hh18tdtuli5e3nd4pufdduo3auhamead.apps.googleusercontent.com',
    iosBundleId: 'com.example.iqoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV2yw-0UrAlgtAd-LdVoyhwoXeXT78ojE',
    appId: '1:1012598441896:ios:37d1fc04abbefed9e8bf9d',
    messagingSenderId: '1012598441896',
    projectId: 'iqoute-d1839',
    storageBucket: 'iqoute-d1839.appspot.com',
    iosClientId: '1012598441896-hh18tdtuli5e3nd4pufdduo3auhamead.apps.googleusercontent.com',
    iosBundleId: 'com.example.iqoute',
  );
}
